cadAp2/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using cadAp2.Models;

namespace cadAp2.Controllers
{
    public class PersonaController : Controller
    {
        static int numeroCadetes = 0;
        static List<Cadete> listaCadetes = new List<Cadete>();
        static List<Persona> listaUsuarios = new List<Persona>();

        private readonly ILogger<PersonaController> _logger;

        public PersonaController(ILogger<PersonaController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View(listaCadetes);
        }

        public IActionResult AltaCadete()
        {
            ViewData["idCad"] = numeroCadetes+1;
            return View();
        }

        // [HttpGet]
        // public IActionResult ActualizarCadete(int id)
        // {
        //     return View(listaCadetes.Select(c => c.Id == id).Single());
        // }

        [HttpPost]
        public IActionResult GuardarCadete(Cadete cadete) {
            cadete.Id = ++numeroCadetes;
            listaCadetes.Add(cadete);
            return RedirectToAction("Index",listaCadetes);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

cadAp2/Views/Persona/AltaCadete.cshtml
@model cadAp2.Models.Persona

@{
    ViewData["Title"] = "Registrar un nuevo Cadete";
}

<h1> @ViewData["Title"] </h1>

<article class="contenedor-form-cadete">
    <form asp-controller="Persona" asp-action="GuardarCadete" method="post">
        <fieldset class="form-group row">

            <legend>Cadete nro. @ViewData["idCad"] </legend>
            <div class="form-group">
                <label for="nom">Nombre: </label>
                    <input class="form-control" type="text" name="Nombre" id="nom" maxlength="50" placeholder="Ingrese el nombre..." required>
                    <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label for="dire">Dirección: </label>
                <input class="form-control" type="text" name="Direccion" id="dire" maxlength="50" placeholder="Ingrese la dirección..." required>
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label for="tel">Teléfono: </label>
                <input class="form-control" type="text" name="Telefono" id="tel" maxlength="50" placeholder="Ingrese el teléfono..." required>
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
            <input type="submit" value="Guardar" class="btn btn-info" />
            </div>
        </fieldset>
    </form>
</article>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

cadAp2/Views/Persona/ConsultaCadete.cshtml
@{
    ViewData["Title"] = "Consulta";
}

@model cadAp2.Models.Persona 

<article>
    <h1 class="text-center"> Consulta de un cadete </h1>

    <p>Código: @Model.Id</p>
    <p>Nombre: @Model.Nombre</p>
    <p>Dirección: @Model.Direccion</p>
    <p>@System.DateTime.Now</p>

</article>

cadAp2/Views/Persona/Index.cshtml
@model IEnumerable<cadAp2.Models.Persona>

@{
    ViewData["Title"] = "Lista de Cadetes";
}

<h1> @ViewData["Title"] </h1>

<p>
    <a asp-action="AltaCadete">Nuevo Cadete</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Cód.
            </th>
            <th>
                Nombre
            </th>
            <th>
                Teléfono
            </th>
            <th>
                Dirección
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var cad in Model) {
        <tr>
            <td>
                @cad.Id
            </td>
            <td>
                @cad.Nombre
            </td>
            <td>
                @cad.Telefono
            </td>
            <td>
                @cad.Direccion
            </td>
            <td>
                <a asp-action="PedidosCadete" asp-route-id="@cad.Id">Pedidos</a> |
                <a asp-action="EditarCadete" asp-route-id="@cad.Id">Editar</a> |
                <a asp-action="BorrarCadete" asp-route-id="@cad.Id">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>